# application.yml

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}  # Externalized with default
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

finnhub:
  api:
    bearerToken: ${FINNHUBB_API_BEARER_TOKEN}                   # Externalized, no default for security

logging:
  level:
    root: INFO
    me.camwalford.finnhubingestionservice: DEBUG  # Adjust package name as needed


