spring:
    application:
        name: finnhub-ingestion-service

finnhub:
  api:
    apiKey: ${FINNHUB_API_KEY:cs1g4hhr01qsperu9s40cs1g4hhr01qsperu9s4g}  # Should be externalized, no default for security


logging:
  level:
    root: INFO
    me.camwalford.finnhubingestionservice: DEBUG  # Adjust package name as needed
    org.springframework.scheduling: DEBUG
    me.camwalford.finnhubingestionservice.service.CompanyNewsFetcher: DEBUG

server:
  port: ${PORT}
