spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        allow.auto.create.topics: true


finnhub:
  api:
    apiKey: ${FINNHUB_API_KEY}  # Externalized, no default for security

kafka:

  topic:
    company-news: company-news-topic
    user-requests: user-requests-topic  # Added user-requests topic
  key:
    company-news: general

logging:
  level:
    root: INFO
    me.camwalford.finnhubingestionservice: DEBUG  # Adjust package name as needed
    org.springframework.scheduling: DEBUG
    me.camwalford.finnhubingestionservice.service.CompanyNewsFetcher: DEBUG

server:
  port: ${PORT:8081}
