# application.yml

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}  # Externalized with default
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.KafkaProtobufSerializer


finnhub:
  api:
    apiKey: ${FINNHUB_API_KEY}                  # Externalized, no default for security

kafka:
  topic:
    market-news: market-news-topic
  key:
    market-news: general





logging:
  level:
    root: INFO
    me.camwalford.finnhubingestionservice: DEBUG  # Adjust package name as needed


