version: '1.0'


# A Docker Compose file for running a full stack sentiment analysis application
services:

# MYSQL database for storing persistent data like user information
# Only used by the backend-api-service
# Requires a volume to persist data
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:sentiment}
      MYSQL_USER: ${MYSQL_USER:admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:admin}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

# API Gateway service which routes requests to the appropriate backend service and handles authentication
  backend-api-service:
    build:
      context: backend-api-service
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST:'mysql'}
      MYSQL_PORT: '3306'
      MYSQL_DATABASE: 'defaultdb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      JWT_KEY: ${JWT_KEY:xuvDXJ27YS+YhsZCFqYkGaYz4YfPrPzfi7dHgZSoVIr1S8UETEfDKtE19V2yr88CIL+WQhXcv8vbE2fUaI2R/w==}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000}
      JAVA_VERSION: ${JAVA_VERSION:21}
    ports:
      - '8080:8080'

# Backend service for fetching company news articles
  finnhub-ingestion-service:
    build:
      context: finnhub-ingestion-service
      dockerfile: ./Dockerfile
      args:
        JAVA_VERSION: ${JAVA_VERSION}
    environment:
      FINNHUB_API_KEY: '${FINNHUB_API_KEY}'

    ports:
      - '8081:8081'

# Python service for sentiment analysis of news articles
  BERT-sentiment-analysis-service:
    build:
      context: BERT-sentiment-analysis-service
      dockerfile: ./Dockerfile
    ports:
      - '8082:8082'

# Frontend REACT application
  web-dashboard-service:
    build:
      context: web-dashboard-service
      dockerfile: ./Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - mysql





