kafka:
  bootstrap_servers: "localhost:9092"
  consumer_topic: "raw-company-news"
  producer_topic: "sentiment-analysis-results"
  group_id: "sentiment-analysis-group"
  auto_offset_reset: "earliest"
