# application.yml

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}  # Externalized with default
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

x:
  api:
    baseUrl: ${X_API_BASE_URL:https://api.twitter.com/2}  # Externalized with default
    bearerToken: ${X_API_BEARER_TOKEN}                   # Externalized, no default for security

logging:
  level:
    root: INFO
    me.camwalford.xingestionservice: DEBUG  # Adjust package name as needed

# Additional configurations can be added below
