spring:
  application:
    name: backend-api-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:marketdb}
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # adjusts the database schema as changes are made to the JPA entities
  docker:
    compose:
      enabled: false

finnhub:
  ingestion:
    service:
      url: ${FINNHUB_INGESTION_SERVICE_URL:http://localhost:8081}

sentiment:
  analysis:
    service:
      url: ${BERT_SENTIMENT_ANALYSIS_SERVICE_URL:http://localhost:8082}

cors:
  allowed-origins:
    - ${WEB_DASHBOARD_SERVICE_URL:http://localhost:3000}


jwt:
  key: ${JWT_KEY:xuvDXJ27YS+YhsZCFqYkGaYz4YfPrPzfi7dHgZSoVIr1S8UETEfDKtE19V2yr88CIL+WQhXcv8vbE2fUaI2R/w==} # Base64 encoded key, default is this random key for development
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000} #1 hour
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000} #24 hours

server:
  port: ${PORT:8080}

logging:
    level:
      org:
        springframework:
          security: DEBUG
